apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity
spec:
  replicas: 2
  selector:
    matchLabels:
        app: app
  template:
    metadata:
      name: udacity
      labels:
        app: app
    spec:
      containers:
      - name: udacity
        image: 372839978247.dkr.ecr.eu-west-1.amazonaws.com/udacity:latest
        ports:
        - containerPort: 80